import type { INodeProperties } from 'n8n-workflow';
import { jsonBodyField, optionalQuery } from '../shared/descriptions';

const r = { resource: ['agent'] };
const show = (...ops: string[]) => ({ show: { ...r, operation: ops } });
const bodyRoute = '={{ JSON.parse($parameter.body || "{}") }}';

export const agentDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: r },
		options: [
			{
				name: 'List Categories',
				value: 'listCategories',
				action: 'List agent categories',
				description: 'List agent categories',
				routing: { request: { method: 'GET', url: '/agents/categories' } },
			},
			{
				name: 'Create Category',
				value: 'createCategory',
				action: 'Create an agent category',
				description: 'Create an agent category',
				routing: { request: { method: 'POST', url: '/agents/categories' } },
			},
			{
				name: 'Update Category',
				value: 'updateCategory',
				action: 'Update an agent category',
				description: 'Update an agent category',
				routing: {
					request: { method: 'PATCH', url: '=/agents/categories/{{$parameter.categoryId}}' },
				},
			},
			{
				name: 'Delete Category',
				value: 'deleteCategory',
				action: 'Delete an agent category',
				description: 'Delete an agent category',
				routing: {
					request: { method: 'DELETE', url: '=/agents/categories/{{$parameter.categoryId}}' },
				},
			},
			{
				name: 'List Configurations',
				value: 'listConfigurations',
				action: 'List agent configurations',
				description: 'List agent configurations',
				routing: { request: { method: 'GET', url: '/agents/configurations' } },
			},
			{
				name: 'Create Configuration',
				value: 'createConfiguration',
				action: 'Create an agent configuration',
				description: 'Create an agent configuration',
				routing: {
					request: { method: 'POST', url: '/agents/configurations', body: bodyRoute },
				},
			},
			{
				name: 'Update Configuration',
				value: 'updateConfiguration',
				action: 'Update an agent configuration',
				description: 'Update an agent configuration',
				routing: {
					request: {
						method: 'PATCH',
						url: '=/agents/configurations/{{$parameter.configId}}',
						body: bodyRoute,
					},
				},
			},
			{
				name: 'Archive Configuration',
				value: 'archiveConfiguration',
				action: 'Archive an agent configuration',
				description: 'Soft-delete an agent configuration',
				routing: {
					request: { method: 'DELETE', url: '=/agents/configurations/{{$parameter.configId}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get an agent configuration',
				description: 'Get an agent configuration by ID',
				routing: { request: { method: 'GET', url: '=/agents/{{$parameter.agentId}}' } },
			},
			{
				name: 'Create Workflow With AI',
				value: 'createWorkflowWithAI',
				action: 'Create a workflow using AI',
				description: 'Create a workflow using AI from a conversation',
				routing: { request: { method: 'POST', url: '/agents/workflows/create-with-ai' } },
			},
			{
				name: 'Validate Form With AI',
				value: 'validateForm',
				action: 'Validate form data using AI',
				description: 'Validate form data using AI',
				routing: { request: { method: 'POST', url: '/agents/forms/validate-with-ai' } },
			},
			{
				name: 'Transcribe Audio',
				value: 'transcribe',
				action: 'Transcribe audio',
				description: 'Transcribe base64-encoded audio',
				routing: { request: { method: 'POST', url: '/agents/audio/transcribe' } },
			},
		],
		default: 'listConfigurations',
	},
	{
		displayName: 'Category ID',
		name: 'categoryId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: show('updateCategory', 'deleteCategory'),
		description: 'UUID of the agent category',
	},
	{
		displayName: 'Config ID',
		name: 'configId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: show('updateConfiguration', 'archiveConfiguration'),
		description: 'UUID of the agent configuration',
	},
	{
		displayName: 'Agent ID',
		name: 'agentId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: show('get'),
		description: 'UUID of the agent configuration',
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: show('createCategory', 'updateCategory'),
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Messages (JSON)',
		name: 'messages',
		type: 'json',
		required: true,
		default: '[]',
		displayOptions: show('createWorkflowWithAI'),
		description: 'Array of conversation messages',
		routing: { send: { type: 'body', property: 'messages', value: '={{ JSON.parse($value) }}' } },
	},
	{
		displayName: 'Company ID',
		name: 'aiCompanyId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: show('createWorkflowWithAI'),
		description: 'UUID of the company',
		routing: { send: { type: 'body', property: 'companyId' } },
	},
	{
		displayName: 'Company ID',
		name: 'validateCompanyId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: show('validateForm'),
		description: 'UUID of the company',
		routing: { send: { type: 'body', property: 'company_id' } },
	},
	{
		displayName: 'Data (JSON)',
		name: 'data',
		type: 'json',
		required: true,
		default: '{}',
		displayOptions: show('validateForm'),
		description: 'Form data to validate',
		routing: { send: { type: 'body', property: 'data', value: '={{ JSON.parse($value) }}' } },
	},
	{
		displayName: 'Validation Rule',
		name: 'validationRule',
		type: 'string',
		required: true,
		default: '',
		typeOptions: { rows: 3 },
		displayOptions: show('validateForm'),
		routing: { send: { type: 'body', property: 'validation_rule' } },
	},
	{
		displayName: 'Audio (Base64)',
		name: 'audio',
		type: 'string',
		required: true,
		default: '',
		displayOptions: show('transcribe'),
		description: 'Base64-encoded audio data',
		routing: { send: { type: 'body', property: 'audio' } },
	},
	optionalQuery(
		'Include Archived',
		'includeArchived',
		'agent',
		['listConfigurations', 'get'],
		'Super-admin/API-key only. Include archived configurations.',
		'boolean',
	),
	jsonBodyField(['createConfiguration', 'updateConfiguration'], 'agent'),
];
